# Build stage
FROM node:24-alpine as build

WORKDIR /app

COPY . .

RUN npm install
RUN chmod -R +x node_modules/.bin
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]