# Build stage
FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY bot/go.mod bot/go.sum ./
RUN go mod download

COPY . .
WORKDIR /app/bot
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main .

# Runtime stage
FROM gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=builder /app/bot/main .

EXPOSE 8081

USER nonroot:nonroot

CMD ["./main"]