CREATE TABLE users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,

    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    company_name VARCHAR(255),
    role INT DEFAULT 0
);

CREATE TABLE visit_cards (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,

    title VARCHAR(255) NOT NULL,
    description LONGTEXT,
    logo_url VARCHAR(255),
    domain VARCHAR(255) UNIQUE,
    telegram_bot_token VARCHAR(255),
    token_valid BOOLEAN DEFAULT TRUE,
    token_error_message VARCHAR(255) DEFAULT '',
    view_count INT DEFAULT 0,
    bot_view_count INT DEFAULT 0,

    user_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE visit_card_views (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,

    visit_card_id BIGINT UNSIGNED NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    last_viewed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (visit_card_id) REFERENCES visit_cards(id) ON DELETE CASCADE
);

CREATE TABLE visit_card_bot_views (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,

    visit_card_id BIGINT UNSIGNED NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    last_viewed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (visit_card_id) REFERENCES visit_cards(id) ON DELETE CASCADE
);